package com.westly.neribovault.core.design

import androidx.compose.ui.graphics.Color

// Light palette
internal val LightBackground = Color(0xFFF7F5F0)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightSurfaceVariant = Color(0xFFEFECE5)
internal val LightOutlineVariant = Color(0xFFE4DFD3)
internal val LightOutline = Color(0xFFB9B3A5)
internal val LightOnSurface = Color(0xFF1C1B18)
internal val LightOnSurfaceVariant = Color(0xFF6B675E)
internal val LightPrimary = Color(0xFF2F6B4F)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFDDEBE2)
internal val LightOnPrimaryContainer = Color(0xFF17402D)
internal val LightError = Color(0xFFB3402F)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFF6DDD8)
internal val LightOnErrorContainer = Color(0xFF4A1A13)
internal val LightSuccess = Color(0xFF2E7D5B)
internal val LightWarning = Color(0xFFB7791F)
internal val LightInverseSurface = Color(0xFF2A2926)
internal val LightInverseOnSurface = Color(0xFFF7F5F0)

// Dark palette
internal val DarkBackground = Color(0xFF121412)
internal val DarkSurface = Color(0xFF1A1D1A)
internal val DarkSurfaceVariant = Color(0xFF242824)
internal val DarkOutlineVariant = Color(0xFF2E322D)
internal val DarkOutline = Color(0xFF4A4F48)
internal val DarkOnSurface = Color(0xFFECEAE3)
internal val DarkOnSurfaceVariant = Color(0xFFA3A095)
internal val DarkPrimary = Color(0xFF86C7A5)
internal val DarkOnPrimary = Color(0xFF0D2A1B)
internal val DarkPrimaryContainer = Color(0xFF1E3A2B)
internal val DarkOnPrimaryContainer = Color(0xFFC6E6D3)
internal val DarkError = Color(0xFFE59A8C)
internal val DarkOnError = Color(0xFF3B1410)
internal val DarkErrorContainer = Color(0xFF4A2621)
internal val DarkOnErrorContainer = Color(0xFFF6DDD8)
internal val DarkSuccess = Color(0xFF86C7A5)
internal val DarkWarning = Color(0xFFE0B15A)
internal val DarkInverseSurface = Color(0xFFECEAE3)
internal val DarkInverseOnSurface = Color(0xFF1C1B18)
