package com.westly.neribovault.core.design

import androidx.compose.ui.graphics.Color

// Light palette
internal val LightBackground = Color(0xFFFAF8F4)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightSurfaceVariant = Color(0xFFF1EEE8)
internal val LightOutlineVariant = Color(0xFFE7E3DA)
internal val LightOutline = Color(0xFFBDB8AC)
internal val LightOnSurface = Color(0xFF1A1917)
internal val LightOnSurfaceVariant = Color(0xFF6F6B63)
internal val LightPrimary = Color(0xFFC25E0C)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFFBE6D3)
internal val LightOnPrimaryContainer = Color(0xFF5A2A05)
internal val LightError = Color(0xFFB3402F)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFF6DDD8)
internal val LightOnErrorContainer = Color(0xFF4A1A13)
internal val LightSuccess = Color(0xFF2E7D5B)
internal val LightWarning = Color(0xFFB7791F)
internal val LightInverseSurface = Color(0xFF2A2926)
internal val LightInverseOnSurface = Color(0xFFFAF8F4)
internal val LightVaultIcon = Color(0xFF1A1917)

// Dark palette: calm charcoal, cards barely lifted from the background, hairline borders,
// muted secondary text, soft light-gray vault icons. Orange (primary) is kept for logo, active nav and FAB.
internal val DarkBackground = Color(0xFF111112)
internal val DarkSurface = Color(0xFF151516)
internal val DarkSurfaceVariant = Color(0xFF1B1B1C)
internal val DarkOutlineVariant = Color(0xFF232324)
internal val DarkOutline = Color(0xFF4A4946)
internal val DarkOnSurface = Color(0xFFE9E7E2)
internal val DarkOnSurfaceVariant = Color(0xFF8B8881)
internal val DarkPrimary = Color(0xFFE08A1E)
internal val DarkOnPrimary = Color(0xFF1F1100)
internal val DarkPrimaryContainer = Color(0xFF2B2016)
internal val DarkOnPrimaryContainer = Color(0xFFE6C9A6)
internal val DarkError = Color(0xFFE59A8C)
internal val DarkOnError = Color(0xFF3B1410)
internal val DarkErrorContainer = Color(0xFF4A2621)
internal val DarkOnErrorContainer = Color(0xFFF6DDD8)
internal val DarkSuccess = Color(0xFF86C7A5)
internal val DarkWarning = Color(0xFFE0B15A)
internal val DarkInverseSurface = Color(0xFFF2EFE9)
internal val DarkInverseOnSurface = Color(0xFF1A1917)
internal val DarkVaultIcon = Color(0xFFC8C5BE)
