package com.westly.neribovault.feature.accounts.editor

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Slider
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import com.westly.neribovault.core.design.NeriboTheme
import com.westly.neribovault.core.ui.components.ButtonStyle
import com.westly.neribovault.core.ui.components.NeriboButton
import kotlin.math.roundToInt

/** A slim four-segment strength bar with the strength words under it. Empty for no password. */
@Composable
fun PasswordStrengthBar(password: String, modifier: Modifier = Modifier) {
    val spacing = NeriboTheme.spacing
    val colors = MaterialTheme.colorScheme
    val score = PasswordStrength.score(password)
    val filled = if (password.isEmpty()) 0 else maxOf(score, 1)
    Column(modifier = modifier.fillMaxWidth()) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(spacing.xs),
        ) {
            for (segment in 1..4) {
                Box(
                    modifier = Modifier
                        .weight(1f)
                        .height(4.dp)
                        .clip(RoundedCornerShape(2.dp))
                        .background(if (segment <= filled) colors.primary else colors.surfaceVariant),
                )
            }
        }
        if (password.isNotEmpty()) {
            Text(
                text = PasswordStrength.label(score),
                style = MaterialTheme.typography.labelSmall,
                color = colors.onSurfaceVariant,
                modifier = Modifier.padding(top = spacing.xs),
            )
        }
    }
}

/**
 * Makes a password: length 8 to 64, the four character groups, look-alike characters off by
 * default. [onUse] gets the chosen password; nothing is copied or logged.
 */
@Composable
fun PasswordGeneratorDialog(
    onDismiss: () -> Unit,
    onUse: (String) -> Unit,
) {
    val spacing = NeriboTheme.spacing
    val colors = MaterialTheme.colorScheme
    var length by rememberSaveable { mutableStateOf(16) }
    var lower by rememberSaveable { mutableStateOf(true) }
    var upper by rememberSaveable { mutableStateOf(true) }
    var digits by rememberSaveable { mutableStateOf(true) }
    var symbols by rememberSaveable { mutableStateOf(true) }
    var avoidAmbiguous by rememberSaveable { mutableStateOf(true) }
    var nonce by rememberSaveable { mutableStateOf(0) }
    // The password itself is never saved with the screen state.
    var generated by remember { mutableStateOf("") }

    LaunchedEffect(length, lower, upper, digits, symbols, avoidAmbiguous, nonce) {
        generated = PasswordGenerator.generate(length, lower, upper, digits, symbols, avoidAmbiguous)
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        shape = MaterialTheme.shapes.large,
        containerColor = colors.surface,
        title = {
            Text(
                text = "Generate a password",
                style = MaterialTheme.typography.titleLarge,
                color = colors.onSurface,
            )
        },
        text = {
            Column(modifier = Modifier.verticalScroll(rememberScrollState())) {
                Text(
                    text = generated,
                    style = MaterialTheme.typography.bodyLarge.copy(fontFamily = FontFamily.Monospace),
                    color = colors.onSurface,
                    modifier = Modifier
                        .fillMaxWidth()
                        .heightIn(min = 56.dp)
                        .clip(MaterialTheme.shapes.medium)
                        .background(colors.surfaceVariant)
                        .padding(spacing.md),
                )
                Spacer(modifier = Modifier.height(spacing.sm))
                PasswordStrengthBar(password = generated)
                Spacer(modifier = Modifier.height(spacing.md))
                Text(
                    text = "Length: $length",
                    style = MaterialTheme.typography.labelLarge,
                    color = colors.onSurfaceVariant,
                )
                Slider(
                    value = length.toFloat(),
                    onValueChange = { length = it.roundToInt().coerceIn(8, 64) },
                    valueRange = 8f..64f,
                    steps = 55,
                )
                GeneratorSwitch("Lower case", lower) { lower = it }
                GeneratorSwitch("Upper case", upper) { upper = it }
                GeneratorSwitch("Digits", digits) { digits = it }
                GeneratorSwitch("Symbols", symbols) { symbols = it }
                GeneratorSwitch("Avoid look-alike characters", avoidAmbiguous) { avoidAmbiguous = it }
                Spacer(modifier = Modifier.height(spacing.sm))
                NeriboButton(
                    text = "Regenerate",
                    onClick = { nonce += 1 },
                    modifier = Modifier.fillMaxWidth(),
                    style = ButtonStyle.Secondary,
                )
            }
        },
        confirmButton = {
            TextButton(onClick = { if (generated.isNotEmpty()) onUse(generated) }) {
                Text(
                    text = "Use this password",
                    style = MaterialTheme.typography.labelLarge,
                    color = colors.primary,
                )
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text(
                    text = "Cancel",
                    style = MaterialTheme.typography.labelLarge,
                    color = colors.onSurfaceVariant,
                )
            }
        },
    )
}

@Composable
private fun GeneratorSwitch(label: String, checked: Boolean, onChange: (Boolean) -> Unit) {
    Row(
        modifier = Modifier.fillMaxWidth().heightIn(min = 48.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodyLarge,
            color = MaterialTheme.colorScheme.onSurface,
            modifier = Modifier.weight(1f),
        )
        Switch(checked = checked, onCheckedChange = onChange)
    }
}
