name: Generate debug keystore
on:
  workflow_dispatch:
jobs:
  keystore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Generate keystore
        run: >
          keytool -genkeypair -v
          -keystore neribo-debug.keystore
          -alias neribodebug
          -keyalg RSA -keysize 2048 -validity 36500
          -storepass android -keypass android
          -dname "CN=Neribo Vault Debug, O=Westly Ibiese, C=NG"
      - uses: actions/upload-artifact@v4
        with:
          name: neribo-debug-keystore
          path: neribo-debug.keystore
